// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cleqfnrbiqpxpzxkatda.supabase.co";
//const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsZXFmbmJpYnB4cHp4a2F0ZGEiLCJyb2xlIjoiYW5vbiIsImlhdCI6MTczNDk2NDYxNSwiZXhwIjoyMDUwNTQwNjE1fQ.sb_publishable_bGMmJHoaG9v29DQ4GrvuKA_BvHrHKf_";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_bGMmJHoaG9v29DQ4GrvuKA_BvHrHKf_";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});